{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "408ea201",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 143, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3301, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 447, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1264, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 711, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    with util.safe_reraise():\n",
      "         ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 175, in _do_get\n",
      "    return self._create_connection()\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 388, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 673, in __init__\n",
      "    self.__connect()\n",
      "    ~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 899, in __connect\n",
      "    with util.safe_reraise():\n",
      "         ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 895, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 661, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 629, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 365, in __init__\n",
      "    self.connect()\n",
      "    ~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 681, in connect\n",
      "    self._request_authentication()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 958, in _request_authentication\n",
      "    auth_packet = self._read_packet()\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 782, in _read_packet\n",
      "    packet.raise_for_error()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\protocol.py\", line 219, in raise_for_error\n",
      "    err.raise_mysql_exception(self._data)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\err.py\", line 150, in raise_mysql_exception\n",
      "    raise errorclass(errno, errval)\n",
      "pymysql.err.OperationalError: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "        connect_str,\n",
      "    ...<2 lines>...\n",
      "        creator=args.creator,\n",
      "    )\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sql\\connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "                               ~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3277, in connect\n",
      "    return self._connection_cls(self)\n",
      "           ~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        err, dialect, engine\n",
      "        ^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2440, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 143, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3301, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 447, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1264, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 711, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    with util.safe_reraise():\n",
      "         ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 175, in _do_get\n",
      "    return self._create_connection()\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 388, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 673, in __init__\n",
      "    self.__connect()\n",
      "    ~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 899, in __connect\n",
      "    with util.safe_reraise():\n",
      "         ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 895, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 661, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 629, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 365, in __init__\n",
      "    self.connect()\n",
      "    ~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 681, in connect\n",
      "    self._request_authentication()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 958, in _request_authentication\n",
      "    auth_packet = self._read_packet()\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\connections.py\", line 782, in _read_packet\n",
      "    packet.raise_for_error()\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\protocol.py\", line 219, in raise_for_error\n",
      "    err.raise_mysql_exception(self._data)\n",
      "    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Apprenant\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pymysql\\err.py\", line 150, in raise_mysql_exception\n",
      "    raise errorclass(errno, errval)\n",
      "sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['mysql+pymysql://root:***@localhost:3306'])\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from IPython.core.magic import register_line_magic\n",
    " #Récupèrelemotdepassedepuislavariabled'environnement\n",
    "password = os.environ.get(\"MYSQL_PASSWORD\")\n",
    " #Vérifiequelemotdepasseestbienrécupéré\n",
    "if password is None:\n",
    "    raiseValueError(\"La variables d'environnement MYSQL_PASSWORD n'est pas définie!\")\n",
    "connection_string= f\"mysql+pymysql://root:{password}@localhost:3306\"\n",
    " #Rechargel'extensionSQL\n",
    "%reload_ext sql\n",
    " #ConnecteàMySQL\n",
    "%sql $connection_string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "095c4e62",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * mysql+pymysql://root:***@localhost:3306\n",
      "(pymysql.err.OperationalError) (2006, \"MySQL server has gone away (ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))\")\n",
      "[SQL: # --Création de la base\n",
      "CREATE DATABASE IF NOT EXISTS ia_educative;]\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n"
     ]
    }
   ],
   "source": [
    "%%sql\n",
    "\n",
    "# --Création de la base\n",
    "CREATE DATABASE IF NOT EXISTS ia_educative;\n",
    "USE ia_educative;\n",
    " \n",
    "#  --Suppression des tables si elles existent déjà\n",
    " \n",
    "DROP TABLE IF EXISTS role;\n",
    "DROP TABLE IF EXISTS matieres;\n",
    "DROP TABLE IF EXISTS niveau;\n",
    "DROP TABLE IF EXISTS etudiants;\n",
    "DROP TABLE IF EXISTS agent;\n",
    "DROP TABLE IF EXISTS session_conversation;\n",
    "DROP TABLE IF EXISTS message;\n",
    "\n",
    "# --Création des tables\n",
    "CREATE TABLE role(\n",
    "   id_role VARCHAR(50),\n",
    "   nom_role VARCHAR(50) NOT NULL,\n",
    "   PRIMARY KEY(id_role)\n",
    ");\n",
    "\n",
    "CREATE TABLE matieres(\n",
    "   id_matieres VARCHAR(50),\n",
    "   nom_matieres VARCHAR(50) NOT NULL,\n",
    "   description_matiere VARCHAR(50),\n",
    "   PRIMARY KEY(id_matieres)\n",
    ");\n",
    "\n",
    "CREATE TABLE niveau(\n",
    "   id_niveau VARCHAR(50),\n",
    "   libelle_niveau VARCHAR(50),\n",
    "   PRIMARY KEY(id_niveau)\n",
    ");\n",
    "\n",
    "CREATE TABLE etudiants(\n",
    "   id_users VARCHAR(50),\n",
    "   nom VARCHAR(50) NOT NULL,\n",
    "   prenom VARCHAR(50) NOT NULL,\n",
    "   email VARCHAR(50) NOT NULL,\n",
    "   avatar VARCHAR(50),\n",
    "   passwordhash VARCHAR(50) NOT NULL,\n",
    "   date_inscription DATETIME NOT NULL,\n",
    "   consentement_rgpd DATETIME NOT NULL,\n",
    "   id_niveau VARCHAR(50) NOT NULL,\n",
    "   id_role VARCHAR(50) NOT NULL,\n",
    "   PRIMARY KEY(id_users),\n",
    "   UNIQUE(email),\n",
    "   FOREIGN KEY(id_niveau) REFERENCES niveau(id_niveau),\n",
    "   FOREIGN KEY(id_role) REFERENCES role(id_role)\n",
    ");\n",
    "\n",
    "CREATE TABLE agent(\n",
    "   id_agents VARCHAR(50),\n",
    "   nom_agent VARCHAR(50) NOT NULL,\n",
    "   type_agent VARCHAR(50) NOT NULL,\n",
    "   avatar_agent DATETIME,\n",
    "   est_actif BOOLEAN,\n",
    "   description VARCHAR(50),\n",
    "   date_creation DATETIME,\n",
    "   prompt_systeme VARCHAR(50),\n",
    "   id_matieres VARCHAR(50),\n",
    "   id_users VARCHAR(50) NOT NULL,\n",
    "   PRIMARY KEY(id_agents),\n",
    "   UNIQUE(nom_agent),\n",
    "   FOREIGN KEY(id_matieres) REFERENCES matieres(id_matieres),\n",
    "   FOREIGN KEY(id_users) REFERENCES etudiants(id_users)\n",
    ");\n",
    "\n",
    "CREATE TABLE session_conversation(\n",
    "   id_session VARCHAR(50),\n",
    "   date_heure_debut DATETIME NOT NULL,\n",
    "   duree_session TIME NOT NULL,\n",
    "   date_heure_fin DATETIME NOT NULL,\n",
    "   id_agents VARCHAR(50) NOT NULL,\n",
    "   id_users VARCHAR(50) NOT NULL,\n",
    "   PRIMARY KEY(id_session),\n",
    "   FOREIGN KEY(id_agents) REFERENCES agent(id_agents),\n",
    "   FOREIGN KEY(id_users) REFERENCES etudiants(id_users)\n",
    ");\n",
    "\n",
    "CREATE TABLE message(\n",
    "   id_message VARCHAR(50),\n",
    "   role VARCHAR(50),\n",
    "   contenu VARCHAR(50),\n",
    "   date_envoi DATETIME,\n",
    "   id_session VARCHAR(50) NOT NULL,\n",
    "   PRIMARY KEY(id_message),\n",
    "   FOREIGN KEY(id_session) REFERENCES session_conversation(id_session)\n",
    ");\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca147da4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
